This code first uses three corners on one image to apply affine transformation, then uses another image to validate the results and caculate errors. Corner coordinates are obtained manually.

In [19]:
import numpy as np
import cv2

# Define original stage points (source),
stage_pts = np.float32([[0,4], [44], [0,0]])

camera_pts =  np.float32([[380, 2960], [3256, 2896], [284, 108]])

# Compute affine transformation matrix
T = cv2.getAffineTransform(stage_pts, camera_pts)

# Print the transformation matrix
print("Affine Transformation Matrix:")
print(T)

# Transform new stage points (from image 2)
new_stage_pts = np.float32([[1,4], [5,4], [1,0]])  # Points from image 2 (stage)

# Convert points using the affine transformation
new_camera_pts = cv2.transform(np.array([new_stage_pts]), T)

# Display transformed points
print("\nTransformed Camera Coordinates:")
print(new_camera_pts[0])

# Calculate error offset
# For simplicity, we calculate the error as the difference between transformed points and expected points.

# Assuming the expected camera points (ground truth for new stage points)
expected_camera_pts = np.float32([[1020, 2944], [3900, 2842], [944, 56]])  # Expected points

# Calculate the error (difference) between transformed points and expected points
error = new_camera_pts[0] - expected_camera_pts
print("\nError Offset:")
print(error)

# Extract scaling factors from the affine transformation matrix (T)
# The scaling factors are in the first two elements of the matrix rows
scale_x = np.linalg.norm(T[0, :2])  # X scaling (magnitude of the first row)
scale_y = np.linalg.norm(T[1, :2])  # Y scaling (magnitude of the second row)

# Scale the error back to stage units
error_in_stage_units = error / np.array([scale_x, scale_y])

print("\nError in Stage Units (mm):")
print(error_in_stage_units)

Affine Transformation Matrix:
[[719.  24. 284.]
 [-16. 713. 108.]]

Transformed Camera Coordinates:
[[1099. 2944.]
 [3975. 2880.]
 [1003.   92.]]

Error Offset:
[[79.  0.]
 [75. 38.]
 [59. 36.]]

Error in Stage Units (mm):
[[0.10981367 0.        ]
 [0.10425348 0.05328252]
 [0.08201274 0.05047818]]
